org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
neo_version=26.1.0.19-beta
neo_version_range=[26.1.0,26.2.0)

mod_id=void_dimension
mod_name=Void Dimension
mod_license=MIT
mod_version=1.1.0-mc26.1+26.1.1-neoforge
mod_group_id=com.chinaex123.void_dimension
